'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class telefono
    Public Property id_tfno As Integer
    Public Property nombre As String
    Public Property apellido1 As String
    Public Property apellido2 As String
    Public Property direccion As String
    Public Property telefono1 As String
    Public Property observaciones As String

End Class
